# Generated by Django 2.2 on 2020-11-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201123_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='Address',
            field=models.CharField(max_length=100),
        ),
    ]
