# Generated by Django 2.2 on 2020-11-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201123_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='DELIVERY_METHOD',
            field=models.CharField(choices=[('Pickup Station', 'Pickup Station'), ('Door Delivery', 'Door Delivery')], default='Door Delivery', max_length=15),
            preserve_default=False,
        ),
    ]
