# Generated by Django 2.2 on 2020-11-25 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201125_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='DELIVERY_METHOD',
            field=models.CharField(choices=[('Pickup Station', 'Pickup Station'), ('Door Delivery', 'Door Delivery')], default='Door Delivery', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.BillingAddress'),
        ),
    ]
